[project]
name = "surveybotsurveydown"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=6.29.5",
    "openai>=1.91.0",
    "psycopg2-binary>=2.9.10",
    "pyyaml>=6.0.2",
]
